---
title: "Sim AR"
author: "Rodrigo Velez"
date: "15/09/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Simulación de un proceso AR(1)

La idea es simular dos procesos AR(1):

Proceso 1: $y_{t}=c+\phi_{1}y_{t-1}+\varepsilon_{t}$; con $c=3$, $y_{1}=100$ y $\phi=0.5$.

Proceso 2: $y_{t}=c+\phi_{1}y_{t-1}+\varepsilon_{t}$; con $c=3$, $y_{1}=100$ y $\phi=-0.5$.

```{r sim}

T = 100       # numero de iteraciones

e = rnorm(T)  # error simulado

c = 3         # constante
phi = 0.5     # coeficiente del rezago

# Construir y

y1 = matrix(data = NA, nrow = T, ncol = 1)
y1[1] = 7

for (t in 2:T) {
  
  y1[t] = c + phi*y1[(t-1)] + e[t]
  
}

plot(y1, type = "l")

```

```{r sim_2}

T = 100       # numero de iteraciones

e = rnorm(T)  # error simulado

c = 3         # constante
phi = -0.5     # coeficiente del rezago

# Construir y

y2 = matrix(data = NA, nrow = T, ncol = 1)
y2[1] = 7

for (t in 2:T) {
  
  y2[t] = c + phi*y2[(t-1)] + e[t]
  
}

plot(y2, type = "l")

```


# Simulacion AR(1) - NO ESTACIONARIO

```{r sim_3}

T = 100       # numero de iteraciones

e = rnorm(T)  # error simulado

c = 3         # constante
phi = 1.5     # coeficiente del rezago

# Construir y

y3 = matrix(data = NA, nrow = T, ncol = 1)
y3[1] = 7

for (t in 2:T) {
  
  y3[t] = c + phi*y3[(t-1)] + e[t]
  
}

plot(y3, type = "l")

```

```{r sim_4}

T = 100       # numero de iteraciones

e = rnorm(T)  # error simulado

c = 3         # constante
phi = -1.5     # coeficiente del rezago

# Construir y

y4 = matrix(data = NA, nrow = T, ncol = 1)
y4[1] = 7

for (t in 2:T) {
  
  y4[t] = c + phi*y4[(t-1)] + e[t]
  
}

plot(y4, type = "l")

```

```{r sim_5}

T = 100       # numero de iteraciones

e = rnorm(T)  # error simulado

c = 3         # constante
phi = -1.0     # coeficiente del rezago

# Construir y

y5 = matrix(data = NA, nrow = T, ncol = 1)
y5[1] = 0

for (t in 2:T) {
  
  y5[t] = c + phi*y5[(t-1)] + e[t]
  
}

plot(y5, type = "l")

```